server:
  port: 8082

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      client-id: clientId

  boot:
    admin:
      client:
        url: http://localhost:8082/admin
      context-path: /admin

management:
  endpoints:
    web:
      exposure:
        include: "*"

config:
  kafka:
    topic: spring-kafka-demo
  async:
    core_pool_size: 2
    max_pool_size: 2
    queue_capacity: 500
    thread_name_prefix: ThreadPoolTaskExecutor